# Generated by Django 3.1.6 on 2021-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userowner_id', models.IntegerField()),
                ('created_at', models.DateField()),
                ('content', models.CharField(max_length=512)),
                ('is_read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('userowner_id', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pickup_starttime', models.DateTimeField()),
                ('pickup_endtime', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('userowner_id', models.IntegerField()),
                ('text', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('1', 'open'), ('2', 'accepted'), ('3', 'deleted')], max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
            ],
        ),
    ]
