# Generated by Django 3.1.6 on 2021-02-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_auto_20210215_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='userowner_id',
            field=models.IntegerField(),
        ),
    ]
