# Generated by Django 3.1.6 on 2021-02-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
    ]
