# Generated by Django 3.1.6 on 2021-02-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0010_request_offer_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='OfferModel',
        ),
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestModel',
        ),
    ]
