# Generated by Django 3.1.6 on 2021-02-16 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0012_offermodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
