# Generated by Django 3.1.6 on 2021-02-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0013_requestmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'accepted'), ('3', 'declined')], default=1, max_length=1),
        ),
    ]
