# Generated by Django 3.1.6 on 2021-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0014_auto_20210216_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'accepted'), (3, 'declined')], default=1),
        ),
    ]
