# Generated by Django 3.1.6 on 2021-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0015_auto_20210216_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
