# Generated by Django 3.1.6 on 2021-02-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_auto_20210215_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='userowner_id',
            field=models.IntegerField(default=0),
        ),
    ]
