# Generated by Django 3.1.6 on 2021-02-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0005_auto_20210215_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='longitude',
        ),
    ]
