# Generated by Django 3.1.6 on 2021-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_auto_20210215_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('userowner_id', models.IntegerField()),
                ('text', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('1', 'open'), ('2', 'accepted'), ('3', 'deleted')], max_length=512)),
            ],
        ),
    ]
