# Generated by Django 3.1.6 on 2021-02-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_auto_20210215_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='offer_id',
            field=models.IntegerField(default=0),
        ),
    ]
