# Generated by Django 3.1.6 on 2021-02-15 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0011_auto_20210215_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
