# Generated by Django 3.1.6 on 2021-02-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_owner_id', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=512)),
            ],
        ),
    ]
